# Generated by Django 3.1.3 on 2020-11-23 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20201123_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userid',
            name='uid',
        ),
        migrations.AlterField(
            model_name='userid',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
