# Generated by Django 3.1.3 on 2020-11-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_auto_20201123_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='uid',
            field=models.CharField(blank=True, default='71e49911-634c-4ee5-a9e1-c5e1fd08affe', max_length=100, null=True, unique=True),
        ),
    ]
