# Generated by Django 3.1.3 on 2020-12-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='current_dir',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cloud',
            name='dir_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cloud',
            name='user_root',
            field=models.CharField(default='', max_length=100),
        ),
    ]
