# Generated by Django 3.1.3 on 2020-12-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_auto_20201207_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='uid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
