# Generated by Django 3.1.3 on 2020-12-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_cloud_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud',
            name='uid',
        ),
    ]
