# Generated by Django 3.1.3 on 2020-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0014_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube',
            field=models.CharField(default='https://www.youtube.com/watch?v=', max_length=500),
        ),
    ]
