# Generated by Django 3.1.3 on 2020-12-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0016_auto_20201215_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
